# Generated by Django 5.2.7 on 2025-10-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='content_html',
            new_name='html_content',
        ),
    ]
